import { forwardRef } from "react";

const COLORS = ["#10B981", "#06B6D4", "#8B5CF6", "#F59E0B", "#EF4444", "#EC4899", "#6366F1", "#14B8A6"];

function formatPct(val) {
  if (val == null) return "—";
  const n = Number(val);
  if (isNaN(n)) return "—";
  return (n >= 0 ? "+" : "") + n.toFixed(2) + "%";
}

function donutSlices(slices, size = 160, stroke = 26) {
  const radius = (size - stroke) / 2;
  const circumference = 2 * Math.PI * radius;
  let offsetAcc = 0;
  return slices.map((s, i) => {
    const dash = (s.pct / 100) * circumference;
    const el = (
      <circle
        key={s.sector}
        cx={size / 2}
        cy={size / 2}
        r={radius}
        fill="none"
        stroke={COLORS[i % COLORS.length]}
        strokeWidth={stroke}
        strokeDasharray={`${dash} ${circumference - dash}`}
        strokeDashoffset={-offsetAcc}
        transform={`rotate(-90 ${size / 2} ${size / 2})`}
      />
    );
    offsetAcc += dash;
    return el;
  });
}

const ReportCard = forwardRef(function ReportCard(
  { healthScore, pnlPct, topPerformer, sectorSlices = [], generatedAt },
  ref
) {
  return (
    <div
      ref={ref}
      style={{
        width: 600,
        padding: 40,
        background: "linear-gradient(135deg, #0B1120 0%, #111827 100%)",
        color: "#F9FAFB",
        fontFamily: "'Inter', 'Helvetica Neue', sans-serif",
      }}
    >
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 32 }}>
        <div style={{ fontSize: 22, fontWeight: 700, letterSpacing: -0.5 }}>Stock-Mate</div>
        <div style={{ fontSize: 11, color: "#9CA3AF", textTransform: "uppercase", letterSpacing: 2 }}>Portfolio Report Card</div>
      </div>

      <div style={{ display: "flex", gap: 24, marginBottom: 32 }}>
        <div style={{ flex: 1, background: "rgba(255,255,255,0.05)", borderRadius: 16, padding: 24, textAlign: "center" }}>
          <div style={{ fontSize: 11, color: "#9CA3AF", textTransform: "uppercase", letterSpacing: 1.5, marginBottom: 8 }}>Health Score</div>
          <div style={{ fontSize: 40, fontWeight: 700 }}>{healthScore != null ? Math.round(healthScore) : "—"}</div>
        </div>
        <div style={{ flex: 1, background: "rgba(255,255,255,0.05)", borderRadius: 16, padding: 24, textAlign: "center" }}>
          <div style={{ fontSize: 11, color: "#9CA3AF", textTransform: "uppercase", letterSpacing: 1.5, marginBottom: 8 }}>Total P&L</div>
          <div style={{ fontSize: 40, fontWeight: 700, color: (pnlPct ?? 0) >= 0 ? "#10B981" : "#EF4444" }}>{formatPct(pnlPct)}</div>
        </div>
      </div>

      {topPerformer && (
        <div style={{ background: "rgba(16,185,129,0.1)", border: "1px solid rgba(16,185,129,0.25)", borderRadius: 16, padding: "16px 20px", marginBottom: 32 }}>
          <span style={{ fontSize: 13, color: "#9CA3AF" }}>Top performer: </span>
          <span style={{ fontSize: 14, fontWeight: 700 }}>{topPerformer.symbol}</span>
          <span style={{ fontSize: 14, fontWeight: 700, color: "#10B981", marginLeft: 8 }}>{formatPct(topPerformer.pnlPct)}</span>
        </div>
      )}

      {sectorSlices.length > 0 && (
        <div style={{ display: "flex", alignItems: "center", gap: 28, marginBottom: 32 }}>
          <svg width={160} height={160}>{donutSlices(sectorSlices)}</svg>
          <div style={{ flex: 1, display: "flex", flexDirection: "column", gap: 8 }}>
            {sectorSlices.slice(0, 6).map((s, i) => (
              <div key={s.sector} style={{ display: "flex", alignItems: "center", justifyContent: "space-between", fontSize: 12 }}>
                <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                  <div style={{ width: 10, height: 10, borderRadius: "50%", background: COLORS[i % COLORS.length] }} />
                  <span style={{ color: "#D1D5DB" }}>{s.sector}</span>
                </div>
                <span style={{ color: "#9CA3AF" }}>{s.pct.toFixed(1)}%</span>
              </div>
            ))}
          </div>
        </div>
      )}

      <div style={{ borderTop: "1px solid rgba(255,255,255,0.1)", paddingTop: 16, display: "flex", justifyContent: "space-between", fontSize: 11, color: "#6B7280" }}>
        <span>Generated by Stock-Mate</span>
        <span>{generatedAt}</span>
      </div>
    </div>
  );
});

export default ReportCard;
